apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry-app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-app
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        app: registry-app
    spec:
      imagePullSecrets:
        - name: registry-regcreds
      containers:
        - name: registry-app
          image: {{ .Values.DOCKER_REGISTRY }}app{{ .Values.DOCKER_TAG }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources: {}
          env:
            - name: APP_BASE_URL
              value: {{ .Values.HIVE_APP_BASE_URL }}
            - name: AUTH_ORGANIZATION_OIDC
              value: {{ .Values.AUTH_ORGANIZATION_OIDC | quote }}
            - name: AUTH_REQUIRE_EMAIL_VERIFICATION
              value: {{ .Values.AUTH_REQUIRE_EMAIL_VERIFICATION | quote }}
            - name: EMAILS_ENDPOINT
              value: http://emails.{{ .Release.Namespace }}.svc:{{ .Values.EMAILS_EXPOSED_PORT }}
            - name: GRAPHQL_ENDPOINT
              value: http://server.{{ .Release.Namespace }}.svc:{{ .Values.SERVER_EXPOSED_PORT }}/graphql
            - name: NODE_ENV
              value: production
            - name: PORT
              value: {{ .Values.APP_CONTAINER_PORT | quote }}
            - name: SERVER_ENDPOINT
              value: http://server.{{ .Release.Namespace }}.svc:{{ .Values.SERVER_EXPOSED_PORT }}
            - name: SUPERTOKENS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: supertokensApiKey
            - name: SUPERTOKENS_CONNECTION_URI
              value: http://supertokens.{{ .Release.Namespace }}.svc:3567
      restartPolicy: Always
status: {}
