apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  ports:
    - name: "29092" # TODO: PERZ-269 move into config
      port: 29092
      targetPort: 29092
  selector:
    io.kompose.service: broker