apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: broker
    spec:
      containers:
        # TODO: PERZ-269 move into values ?
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.{{ .Release.Namespace }}.svc:2181
          image: confluentinc/cp-kafka:7.3.3
          livenessProbe:
            exec:
              command:
                - cub
                - kafka-ready
                - "1"
                - "5"
                - -b
                - 127.0.0.1:9092
                - -c
                - /etc/kafka/kafka.properties
            failureThreshold: 6
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
          name: broker
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: broker-claim0
      hostname: broker
      restartPolicy: Always
      volumes:
        - name: broker-claim0
          persistentVolumeClaim:
            claimName: broker-claim0
status: {}
