apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: clickhouse
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_PASSWORD
              value: {{ .Values.CLICKHOUSE_PASSWORD }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.CLICKHOUSE_USER }}
          image: clickhouse/clickhouse-server:23.3-alpine
          livenessProbe:
            exec:
              command:
                - wget
                - --spider
                - -q
                - localhost:8123/ping
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          name: clickhouse
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-claim0
      restartPolicy: Always
      volumes:
        - name: clickhouse-claim0
          persistentVolumeClaim:
            claimName: clickhouse-claim0
status: {}
