apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  ports:
    - name: "8123" # TODO: PERZ-269 move into config
      port: 8123
      targetPort: 8123
  selector:
    io.kompose.service: clickhouse