# Hive cannot use Apollo Federation v2 libraries directly due to licensing
# Therefore we use a separate composition service that uses Apollo Federation v2
# More information: https://the-guild.dev/graphql/hive/docs/management/external-schema-composition
# More information. https://github.com/kamilkisiela/graphql-hive/tree/main/packages/services/external-composition/federation-2
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: composition
  name: composition
spec:
  ports:
    - name: "3069"
      port: {{ .Values.COMPOSITION_PORT }}
      targetPort: {{ .Values.COMPOSITION_PORT }}
  selector:
    io.kompose.service: composition
status:
  loadBalancer: {}
