# Hive cannot use Apollo Federation v2 libraries directly due to licensing
# Therefore we use a separate composition service that uses Apollo Federation v2
# More information: https://the-guild.dev/graphql/hive/docs/management/external-schema-composition
# More information. https://github.com/kamilkisiela/graphql-hive/tree/main/packages/services/external-composition/federation-2
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: composition
  name: composition
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: composition
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: composition
    spec:
      imagePullSecrets:
        - name: registry-regcreds
      containers:
        - image: {{ .Values.DOCKER_REGISTRY }}composition-federation-2{{ .Values.DOCKER_TAG }}
          imagePullPolicy: Always
          name: composition
          ports:
            - containerPort: {{ .Values.COMPOSITION_PORT }}
          resources: {}
          env:
            - name: PORT
              value: {{ .Values.COMPOSITION_PORT | quote }}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: compositionSecret
      restartPolicy: Always
status: {}
