apiVersion: v1
kind: Service
metadata:
  name: emails
spec:
  ports:
    - name: "3011"
      port: {{ .Values.EMAILS_EXPOSED_PORT }}
      targetPort: {{ .Values.EMAILS_EXPOSED_PORT }}
  selector:
    io.kompose.service: emails