apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: emails
  name: emails
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emails
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: emails
    spec:
      containers:
        - env:
            - name: EMAIL_FROM
              value: no-reply@graphql-hive.com
            - name: EMAIL_PROVIDER
              value: sendmail
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3011"
            - name: REDIS_HOST
              value: redis.{{ .Release.Namespace }}.svc
            - name: REDIS_PASSWORD
              value: {{ .Values.REDIS_PASSWORD }}
            - name: REDIS_PORT
              value: "6379"
          # TODO: PERZ-269 check if env correctly resolved
          image: {{ .Values.DOCKER_REGISTRY }}emails{{ .Values.DOCKER_TAG }}
          name: emails
          resources: {}
      restartPolicy: Always
status: {}
