apiVersion: v1
kind: Service
metadata:
  name: emails
spec:
  ports:
    - name: "3011" # TODO: PERZ-269 move into config
      port: 3011
      targetPort: 3011
  selector:
    io.kompose.service: emails