apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-hive
  namespace: hive
spec:
  dnsNames:
    - {{ .Values.serverUrl }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: server-hive