###
# https://github.com/kamilkisiela/graphql-hive/tree/main/packages/services/storage
###
apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  # selector:
  #   matchLabels:
  #     io.kompose.service: migrations
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: migrations
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_HOST
              value: clickhouse.{{ .Release.Namespace }}.svc
            - name: CLICKHOUSE_MIGRATOR
              value: "up"
            - name: CLICKHOUSE_PASSWORD
              value: {{ .Values.CLICKHOUSE_PASSWORD }}
            - name: CLICKHOUSE_PORT
              value: "8123" # TODO: PERZ-269 move into values
            - name: CLICKHOUSE_PROTOCOL
              value: "http"
            - name: CLICKHOUSE_USERNAME
              value: {{ .Values.CLICKHOUSE_USER }}
            - name: MIGRATOR
              value: "up"
            - name: POSTGRES_DB
              value: {{ .Values.POSTGRES_DB }}
            - name: POSTGRES_HOST
              value: db.{{ .Release.Namespace }}.svc
            - name: POSTGRES_PASSWORD
              value: {{ .Values.POSTGRES_PASSWORD }}
            - name: POSTGRES_PORT
              value: "5432" # TODO: PERZ-269 move into values
            - name: POSTGRES_USER
              value: {{ .Values.POSTGRES_USER }}
            - name: TS_NODE_TRANSPILE_ONLY
              value: "true"
          # TODO: PERZ-269 check if env ar resolved correctly
          image: {{ .Values.DOCKER_REGISTRY}}storage{{ .Values.DOCKER_TAG }}
          name: migrations
          resources: {}
      restartPolicy: OnFailure
status: {}
