###
# https://github.com/kamilkisiela/graphql-hive/tree/main/packages/services/storage
###
apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: migrations
    spec:
      imagePullSecrets:
        - name: registry-regcreds
      containers:
        - image: {{ .Values.DOCKER_REGISTRY }}storage{{ .Values.DOCKER_TAG }}
          name: migrations
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse.{{ .Release.Namespace }}.svc
            - name: CLICKHOUSE_MIGRATOR
              value: "up"
            - name: CLICKHOUSE_PORT
              value: {{ .Values.CLICKHOUSE_PORT | quote }}
            - name: CLICKHOUSE_PROTOCOL
              value: {{ .Values.CLICKHOUSE_PROTOCOL | quote }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: clickhousePassword
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: clickhouseUser
            - name: MIGRATOR
              value: "up"
            - name: POSTGRES_DB
              value: {{ .Values.POSTGRES_DB | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: postgresPassword
            - name: POSTGRES_USER
              value: {{ .Values.POSTGRES_USER | quote}}
            - name: POSTGRES_HOST
              value: db.{{ .Release.Namespace }}.svc
            - name: POSTGRES_PORT
              value: "5432"
            - name: TS_NODE_TRANSPILE_ONLY
              value: "true"
          resources: {}
      restartPolicy: OnFailure
status: {}
