apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "6379" # TODO: PERZ-269 move into config
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis