apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: "redis"
      port: {{ .Values.REDIS_PORT }}
      targetPort: {{ .Values.REDIS_PORT }}
  selector:
    io.kompose.service: redis