apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: redis
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 1001
      containers:
        - name: redis
          image: bitnami/redis:7.0.10
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          resources: {}
          env:
            - name: REDIS_DISABLE_COMMANDS
              value: FLUSHDB,FLUSHALL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: redisPassword
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: redis-claim0
      restartPolicy: Always
      volumes:
        - name: redis-claim0
          persistentVolumeClaim:
            claimName: redis-claim0
status: {}
