apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: s3-provision-buckets
  name: s3-provision-buckets
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: s3-provision-buckets
    spec:
      containers:
        - name: s3-provision-buckets
          image: quay.io/minio/mc:RELEASE.2022-11-17T21-20-39Z
          env:
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: minioRootPassword
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: minioRootUser
          command:
            - /bin/sh
            -  -xc
            - ' /usr/bin/mc --debug alias set --api="s3v4" myminio http://s3.{{ .Release.Namespace }}.svc:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; sleep 5; /usr/bin/mc --debug ls myminio/artifacts >/dev/null 2>&1 || /usr/bin/mc --debug mb myminio/artifacts;'
          resources: {}
      restartPolicy: OnFailure
status: {}
