# https://hub.docker.com/_/caddy
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: s3-reverse-proxy
  name: s3-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: s3-reverse-proxy
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: s3-reverse-proxy
    spec:
      containers:
        - image: caddy:2.6.4-alpine
          name: s3-reverse-proxy
          args:
            - caddy
            - reverse-proxy
            - --from
            - :8083
            - --to
            - s3.{{ .Release.Namespace }}.svc:9000
            - --change-host-header
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}
