apiVersion: v1
kind: Service
metadata:
  name: schema
spec:
  ports:
    - name: "3002" # TODO: PERZ-269 move into config
      port: 3002
      targetPort: 3002
  selector:
    io.kompose.service: schema