apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "cdn-endpoint"
      port: {{ .Values.SERVER_EXPOSED_PORT }}
      targetPort: {{ .Values.SERVER_CONTAINER_PORT }}
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
