apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 3001
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
