apiVersion: v1
kind: Service
metadata:
  name: supertokens
spec:
  ports:
    - name: "3567" # TODO: PERZ-269 move into config
      port: 3567
      targetPort: 3567
  selector:
    io.kompose.service: supertokens