apiVersion: v1
kind: Service
metadata:
  name: supertokens
spec:
  ports:
    - name: "supertokens-api"
      port: {{ .Values.SUPERTOKENS_PORT }}
      targetPort: {{ .Values.SUPERTOKENS_PORT }}
  selector:
    io.kompose.service: supertokens