apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: supertokens
  name: supertokens
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: supertokens
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: supertokens
    spec:
      containers:
        - image: {{ .Values.SUPERTOKENS_IMAGE }}:{{ .Values.SUPERTOKENS_VERSION }}
          name: supertokens
          resources: {}
          env:
            - name: SUPERTOKENS_PORT
              value: {{ .Values.SUPERTOKENS_PORT | quote }}
            - name: ACCESS_TOKEN_BLACKLISTING
              value: "true"
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: supertokensApiKey
            - name: POSTGRESQL_HOST
              value: db.{{ .Release.Namespace }}.svc
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_TABLE_NAMES_PREFIX
              value: supertokens
            - name: POSTGRESQL_DATABASE_NAME
              value: {{ .Values.POSTGRES_DB }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supergraph-registry-secrets
                  key: postgresPassword
            - name: POSTGRESQL_USER
              value: {{ .Values.POSTGRES_USER }}
      restartPolicy: Always
status: {}
