apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: tokens
  name: tokens
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tokens
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: tokens
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3003"
            - name: POSTGRES_DB
              value: {{ .Values.POSTGRES_DB }}
            - name: POSTGRES_HOST
              value: db.hive.svc
            - name: POSTGRES_PASSWORD
              value: {{ .Values.POSTGRES_PASSWORD }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: {{ .Values.POSTGRES_USER }}
            - name: REDIS_HOST
              value: redis.hive.svc
            - name: REDIS_PASSWORD
              value: {{ .Values.REDIS_PASSWORD }}
            - name: REDIS_PORT
              value: "6379"
          image: {{ .Values.DOCKER_REGISTRY }}tokens{{ .Values.DOCKER_TAG }}
          name: tokens
          resources: {}
      restartPolicy: Always
status: {}
