apiVersion: v1
kind: Service
metadata:
  name: tokens
spec:
  ports:
    - name: "3003" # TODO: PERZ-269 move into config
      port: 3003
      targetPort: 3003
  selector:
    io.kompose.service: tokens