apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: usage
  name: usage
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 3006
  selector:
    io.kompose.service: usage
status:
  loadBalancer: {}
