apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: usage
  name: usage
spec:
  ports:
    - name: "usage"
      port: {{ .Values.USAGE_EXPOSED_PORT }}
      targetPort: {{ .Values.USAGE_CONTAINER_PORT }}
  selector:
    io.kompose.service: usage
status:
  loadBalancer: {}
