apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: usage
  name: usage-ingestor
spec:
  ports:
    - name: "usage-ingestor"
      port: {{ .Values.USAGE_INGESTOR_PORT }}
      targetPort: {{ .Values.USAGE_INGESTOR_PORT }}
  selector:
    io.kompose.service: usage-ingestor
status:
  loadBalancer: {}
