apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: webhooks
  name: webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webhooks
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: webhooks
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3005"
            - name: REDIS_HOST
              value: redis.{{ .Release.Namespace }}.svc
            - name: REDIS_PASSWORD
              value: {{ .Values.REDIS_PASSWORD }}
            - name: REDIS_PORT
              value: "6379" # TODO: PERZ-269 move into values
          image: {{ .Values.DOCKER_REGISTRY }}webhooks{{ .Values.DOCKER_TAG }}
          name: webhooks
          resources: {}
      restartPolicy: Always
status: {}
