apiVersion: v1
kind: Service
metadata:
  name: webhooks
spec:
  ports:
    - name: "3005" # TODO: PERZ-269 move into config
      port: 3005
      targetPort: 3005
  selector:
    io.kompose.service: webhooks